---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: foswiki
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: foswiki
      namespace: foswiki
      labels:
        app: foswiki
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: foswiki
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 50%
          maxSurge: 1
      template:
        metadata:
          labels:
            app: foswiki
        spec:
          containers:
          - name: foswiki
            image: cjlove/centos-foswiki
            imagePullPolicy: Never
            ports:
            - containerPort: 80
            volumeMounts:
              - name: wiki
                mountPath: /var/lib/foswiki/data

          terminationGracePeriodSeconds: 30
          volumes:
          - name: wiki
            hostPath:
                path: /home/wiki/data
  - apiVersion: v1
    kind: Service
    metadata:
      name: foswiki
      namespace: foswiki
      labels:
        app: foswiki
    spec:
      type: NodePort
      ports:
      - port: 80
        nodePort: 30000
        protocol: TCP
        name: http
      selector:
        app: foswiki
