---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: foswiki
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: foswiki
      namespace: foswiki
      labels:
        app: foswiki
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: foswiki
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 50%
          maxSurge: 1
      template:
        metadata:
          labels:
            app: foswiki
        spec:
          containers:
          - name: foswiki
            #            image: cjlove/centos-foswiki
            # image: andreysmelter/ubuntu-foswiki
            image: timlegge/docker-foswiki
            imagePullPolicy: IfNotPresent
            lifecycle:
              postStart:
                exec:
                  command:
                    - ln
                    - -fs
                    - /var/www/foswiki/config/LocalSite.cfg
                    - /var/www/foswiki/lib/LocalSite.cfg
            ports:
            - containerPort: 80
            volumeMounts:
              - name: wiki-data
                mountPath: /var/www/foswiki/data
              - name: wiki-cfg
                mountPath: /var/www/foswiki/config

          terminationGracePeriodSeconds: 30
          volumes:
          - name: wiki-data
            hostPath:
                path: /home/wiki/data
          - name: wiki-cfg
            hostPath:
                path: /home/wiki/config
  - apiVersion: v1
    kind: Service
    metadata:
      name: foswiki
      namespace: foswiki
      labels:
        app: foswiki
    spec:
      type: NodePort
      ports:
      - port: 80
        nodePort: 30000
        protocol: TCP
        name: http
      selector:
        app: foswiki
