---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: opengrok
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: opengrok
      namespace: opengrok
      labels:
        app: opengrok
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: opengrok
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 50%
          maxSurge: 1
      template:
        metadata:
          labels:
            app: opengrok
        spec:
          containers:
          - name: opengrok
            image: opengrok/docker
            imagePullPolicy: Always
            ports:
            - containerPort: 8080
            volumeMounts:
              - name: src
                mountPath: /src
          terminationGracePeriodSeconds: 30
          volumes:
          - name: src
            hostPath:
                path: /home/opengrok/Source/
  - apiVersion: v1
    kind: Service
    metadata:
      name: opengrok
      namespace: opengrok
      labels:
        app: opengrok
    spec:
      type: NodePort
      ports:
      - port: 8080
        nodePort: 30001
        protocol: TCP
        name: http
      - port: 22
        nodePort: 30002
        protocol: TCP
        name: ssh
      selector:
        app: opengrok
