---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: wiki-js2
  
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: wiki-js2
      namespace: wiki-js2
      labels:
        app: wiki-js2
    spec:
      replicas: 1
      selector:
        matchLabels: 
          app: wiki-js2
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 50%
          maxSurge: 1
      template:
        metadata:
          labels:
            app: wiki-js2
        spec:
          containers:
          - name: redis
            image: redis:4-alpine
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 6379
            env:
          
          - name: postgres
            image: postgres:9-alpine
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 5432
            env:
            - name: POSTGRES_DB
              value: wiki
            - name: POSTGRES_PASSWORD
              value: wikijsrocks
            - name: POSTGRES_USER
              value: wiki
            volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

          - name: wiki-js
            image: requarks/wiki:dev
            ports:
            - containerPort: 80
            env:
            - name: PORT
              value: "30006"
            - name: DB_TYPE
              value: postgres
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: wikijs
            - name: DB_PASS
              value: wikijsrocks
            - name: DB_NAME
              value: wiki
            - name: REDIS_HOST
              value: "127.0.0.1"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
          
          volumes:
          - name: postgres-data
            hostPath:
                path: /home/wiki/postgres-data

  - apiVersion: v1
    kind: Service
    metadata:
      name: wiki-js2
      namespace: wiki-js2
      labels:
        app: wiki-js2
    spec:
      type: NodePort
      ports:
      - port: 80
        nodePort: 30006
        protocol: TCP
        name: http
      selector:
        app: wiki-js2
